In [ ]:
Practice Assignment for seceond DA 2

In [2]:
transactions = [
    ['Rice', 'Sugar', 'Tea'],
    ['Rice', 'Oil'],
    ['Sugar', 'Tea'],
    ['Rice', 'Sugar'],
    ['Rice', 'Tea', 'Oil'],
    ['Sugar', 'Oil'],
    ['Rice', 'Sugar', 'Tea', 'Oil'],
    ['Tea', 'Biscuits'],
    ['Rice', 'Biscuits'],
    ['Sugar', 'Biscuits']
]
transactions

[['Rice', 'Sugar', 'Tea'],
 ['Rice', 'Oil'],
 ['Sugar', 'Tea'],
 ['Rice', 'Sugar'],
 ['Rice', 'Tea', 'Oil'],
 ['Sugar', 'Oil'],
 ['Rice', 'Sugar', 'Tea', 'Oil'],
 ['Tea', 'Biscuits'],
 ['Rice', 'Biscuits'],
 ['Sugar', 'Biscuits']]

In [9]:
pip install mlxtend

Requirement already satisfied: mlxtend in /usr/local/lib/python3.9/site-packages (0.23.4)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib64/python3.9/site-packages (from mlxtend) (2.0.2)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib64/python3.9/site-packages (from mlxtend) (1.13.1)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib64/python3.9/site-packages (from mlxtend) (2.3.2)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.9/site-packages (from mlxtend) (1.5.3)
Requirement already satisfied: scikit-learn>=1.3.1 in /usr/local/lib64/python3.9/site-packages (from mlxtend) (1.6.1)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib64/python3.9/site-packages (from mlxtend) (3.9.4)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib64/python3.9/site-packages (from matplotlib>=3.0.0->mlxtend) (4.59.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib64/python3.9/site-packages (from matplotlib>=3.0.0->mlxtend) (11.3.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.9/site-packages (from matplotlib>=3.0.0->mlxtend) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/lib/python3.9/site-packages (from matplotlib>=3.0.0->mlxtend) (2.4.7)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.9/site-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib64/python3.9/site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib64/python3.9/site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.7)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.9/site-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: importlib-resources>=3.2.0 in /usr/local/lib/python3.9/site-packages (from matplotlib>=3.0.0->mlxtend) (6.5.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.9/site-packages (from pandas>=0.24.2->mlxtend) (2025.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.9/site-packages (from pandas>=0.24.2->mlxtend) (2025.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.9/site-packages (from scikit-learn>=1.3.1->mlxtend) (3.6.0)
Requirement already satisfied: zipp>=3.1.0 in /usr/local/lib/python3.9/site-packages (from importlib-resources>=3.2.0->matplotlib>=3.0.0->mlxtend) (3.23.0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.15.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Note: you may need to restart the kernel to use updated packages.

In [10]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [11]:
te = TransactionEncoder()
te_array = te.fit(transactions).transform(transactions)
df = pd.DataFrame(te_array, columns=te.columns_)

print(df)

   Biscuits    Oil   Rice  Sugar    Tea
0     False  False   True   True   True
1     False   True   True  False  False
2     False  False  False   True   True
3     False  False   True   True  False
4     False   True   True  False   True
5     False   True  False   True  False
6     False   True   True   True   True
7      True  False  False  False   True
8      True  False   True  False  False
9      True  False  False   True  False

In [24]:
frequent_itemsets = apriori(df, min_support=0.2, use_colnames=True)
print("Frequent Itemsets:")
print(frequent_itemsets)

Frequent Itemsets:
    support            itemsets
0       0.3          (Biscuits)
1       0.4               (Oil)
2       0.6              (Rice)
3       0.6             (Sugar)
4       0.5               (Tea)
5       0.3         (Rice, Oil)
6       0.2        (Sugar, Oil)
7       0.2          (Tea, Oil)
8       0.3       (Sugar, Rice)
9       0.3         (Tea, Rice)
10      0.3        (Tea, Sugar)
11      0.2    (Tea, Rice, Oil)
12      0.2  (Tea, Sugar, Rice)

In [18]:
frequent_itemsets [frequent_itemsets['itemsets'].apply(lambda x: len(x) == 1)]

   support itemsets
0      0.6   (Rice)
1      0.6  (Sugar)
2      0.5    (Tea)

In [26]:
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.5)
print("Association Rules:")
print(rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']])

Association Rules:
      antecedents  consequents  support  confidence      lift
0          (Rice)        (Oil)      0.3    0.500000  1.250000
1           (Oil)       (Rice)      0.3    0.750000  1.250000
2           (Oil)      (Sugar)      0.2    0.500000  0.833333
3           (Oil)        (Tea)      0.2    0.500000  1.000000
4         (Sugar)       (Rice)      0.3    0.500000  0.833333
5          (Rice)      (Sugar)      0.3    0.500000  0.833333
6           (Tea)       (Rice)      0.3    0.600000  1.000000
7          (Rice)        (Tea)      0.3    0.500000  1.000000
8           (Tea)      (Sugar)      0.3    0.600000  1.000000
9         (Sugar)        (Tea)      0.3    0.500000  1.000000
10    (Tea, Rice)        (Oil)      0.2    0.666667  1.666667
11     (Tea, Oil)       (Rice)      0.2    1.000000  1.666667
12    (Oil, Rice)        (Tea)      0.2    0.666667  1.333333
13          (Oil)  (Tea, Rice)      0.2    0.500000  1.666667
14   (Tea, Sugar)       (Rice)      0.2    0.666667  1.111111
15    (Tea, Rice)      (Sugar)      0.2    0.666667  1.111111
16  (Sugar, Rice)        (Tea)      0.2    0.666667  1.333333

In [ ]:
//Check If Frequent Itemsets Are Empty

In [20]:
frequent_itemsets.empty

False

In [ ]:
Generate Rules Using Lift Metric

In [22]:
rules_lift = association_rules(frequent_itemsets, metric="lift", min_threshold=0.6)
rules_lift

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, representativity, leverage, conviction, zhangs_metric, jaccard, certainty, kulczynski]
Index: []